version: '3.8'

services:
  structana:
    image: nginx
    volumes:
      - ./apps/structana:/usr/share/nginx/html:ro
    container_name: structana
    networks:
      - web

  cosmicauracle:
    image: nginx
    volumes:
      - ./apps/cosmicauracle:/usr/share/nginx/html:ro
    container_name: cosmicauracle
    networks:
      - web

  funemployed:
    image: nginx
    volumes:
      - ./apps/funemployed:/usr/share/nginx/html:ro
    container_name: funemployed
    networks:
      - web

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - structana
      - cosmicauracle
      - funemployed
    networks:
      - web

networks:
  web:
