version: '3.8'

services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "npm install && npm start"
    expose:
      - "3000"
    depends_on:
      - mongo
    labels:
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.services.app.loadbalancer.server.port=3000"

  js-backend:
    build: ./js-backend
    labels:
      - "traefik.http.routers.js-backend.rule=PathPrefix(`/api/js`)"
      - "traefik.http.services.js-backend.loadbalancer.server.port=3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

  traefik:
    image: traefik:v2.9
    command:
      - --providers.file.directory=/etc/traefik
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.toml:/etc/traefik/dynamic.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - app


  py-backend:
    build: ./py-backend
    labels:
      - "traefik.http.routers.py-backend.rule=PathPrefix(`/api/py`)"
      - "traefik.http.services.py-backend.loadbalancer.server.port=8000"

  traefik:
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongo-data:
