version: '3.8'

services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "npm install && npm start"
    expose:
      - "3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

  traefik:
    image: traefik:v2.9
    command:
      - --providers.file.directory=/etc/traefik
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./www:/srv/www:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app

volumes:
  mongo-data:
